name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: make install
    
    - name: Run formatting
      run: make format
    
    - name: Run linting
      run: make lint
    
    - name: Run tests
      run: make test
    
    - name: Generate coverage report
      run: make coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
    
    - name: Generate documentation
      run: make docs
    
    - name: Verify documentation
      run: |
        if [ ! -d "docs" ]; then
          echo "Documentation directory not found"
          exit 1
        fi
        if [ ! -f "docs/README.md" ]; then
          echo "Documentation README file not found"
          exit 1
        fi
        # Check for basic documentation structure
        if [ ! -d "docs/modules" ] && [ ! -d "docs/classes" ]; then
          echo "Documentation structure is incomplete"
          exit 1
        fi
    
    - name: Build
      run: make build 